namespace AIC.Core.Identity.Models.Contracts;

using AIC.Core.Data.Contracts;
using AIC.Core.Data.Models.References.Contracts;
using AIC.Core.Identity.Models.Implementations;

public interface IUser : IBaseEntity, IHasOrganisationId
{
    /// <summary>
    ///     Gets or sets the user name for this user.
    /// </summary>

    public string UserName { get; set; }

    /// <summary>
    ///     Gets or sets the email address for this user.
    /// </summary>

    public string Email { get; set; }

    /// <summary>
    ///     Gets or sets a flag indicating if a user has confirmed their email address.
    /// </summary>
    /// <value>True if the email address has been confirmed, otherwise false.</value>

    public bool EmailConfirmed { get; set; }

    /// <summary>
    ///     Gets or sets a telephone number for the user.
    /// </summary>

    public string PhoneNumber { get; set; }

    /// <summary>
    ///     Gets or sets a flag indicating if a user has confirmed their telephone address.
    /// </summary>
    /// <value>True if the telephone number has been confirmed, otherwise false.</value>

    public bool PhoneNumberConfirmed { get; set; }

    /// <summary>
    ///     Gets or sets the external user identifier.
    /// </summary>
    /// <value>The external user identifier.</value>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ExternalUserId
    public string ExternalUserId { get; set; }

    /// <summary>
    ///     Gets or sets the external subscription customer identifier.
    /// </summary>
    /// <value>The external subscription customer identifier.</value>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ExternalSubscriptionCustomerId
    public string ExternalSubscriptionCustomerId { get; set; }

    /// <summary>
    ///     Gets or sets the type.
    /// </summary>
    /// <value>The type.</value>
    public UserType Type { get; set; }

    /// <summary>
    ///     Gets or sets the status.
    /// </summary>
    /// <value>The status.</value>
    public UserStatus Status { get; set; }

    public IProfile Profile { get; set; }
    public IList<IDocument> Documents { get; set; }
    public IList<IHoliday> Holidays { get; set; }
    public IList<IPaymentMethod> PaymentMethods { get; set; }

    public IEnumerable<IdentityRole> Roles { get; set; }
}