namespace AIC.Core.Data.MongoDb.Contracts;

using MongoDB.Driver.GeoJsonObjectModel;
using MongoDB.Driver.GridFS;

public interface IMongoDbFileRepository<TModel, TId> : IMongoDbRepository<TModel, TId>
    where TModel : class, IMongoDbDocument<TId>
    where TId : struct, IEquatable<TId>
{
    /// <summary>
    ///     Searches the by coordinates.
    /// </summary>
    /// <typeparam name="TGeographicModel">The type of the t geographic model.</typeparam>
    /// <typeparam name="TGeographicContextCoordinate">The type of the t geographic context coordinate.</typeparam>
    /// <param name="latitude">The latitude.</param>
    /// <param name="longitude">The longitude.</param>
    /// <returns>Task&lt;IEnumerable&lt;TGeographicModel&gt;&gt;.</returns>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for SearchByCoordinates`2
    Task<IEnumerable<TGeographicModel>> SearchByCoordinates<TGeographicModel,
        TGeographicContextCoordinate>(double latitude, double longitude)
        where TGeographicModel : TModel, IHasGeographicContext<TGeographicContextCoordinate>
        where TGeographicContextCoordinate : GeoJsonCoordinates;

    /// <summary>
    ///     Creates the specified identifier.
    /// </summary>
    /// <param name="id">The identifier.</param>
    /// <param name="model">The model.</param>
    /// <param name="filename">The filename.</param>
    /// <param name="gridFsUploadOptions">The grid fs upload options.</param>
    /// <returns>Task&lt;TId&gt;.</returns>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for CreateAsync
    Task<TId> CreateAsync(TId id, TModel model, string filename = null, GridFSUploadOptions gridFsUploadOptions = null);

    /// <summary>
    ///     Reads the specified identifier.
    /// </summary>
    /// <param name="id">The identifier.</param>
    /// <param name="filename">The filename.</param>
    /// <param name="gridFsDownloadOptions">The grid fs download options.</param>
    /// <param name="gridFsDownloadByNameOptions">The grid fs download by name options.</param>
    /// <returns>Task&lt;TModel&gt;.</returns>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for ReadAsync
    Task<TModel> ReadAsync(TId id, string filename, GridFSDownloadOptions gridFsDownloadOptions = null,
        GridFSDownloadByNameOptions gridFsDownloadByNameOptions = null);
}